# ./docker-compose.yml

version: '3'

services:
  db:
    container_name: db
    build: 
      context: .
      dockerfile: dockerfiles/mysql/Dockerfile_mysql5.5
      #dockerfile: dockerfiles/mysql/Dockerfile_mysql8
    #command: mysqld --default-authentication-plugin=mysql_native_password # Uncomment this for mysql8
    environment:
      MYSQL_ROOT_PASSWORD: dbpass  # This is used by phpmyadmin, if changed must update the PMA_PASSWORD below to match
      MYSQL_DATABASE: dbname
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
    volumes:
      # Store your .sql dumps in a mysql/ directory. This will import them during the setup.
      - ./mysql_dump:/docker-entrypoint-initdb.d
    ports:
      - "9906:3306"
  webserver:
    container_name: web
    build: 
      context: .
      dockerfile: dockerfiles/webserver/Dockerfile_centos7_php53
      #dockerfile: dockerfiles/webserver/Dockerfile_centos7_php72
    depends_on:
      - db
    volumes:
      - ./html/:/var/www/html/
      - ./setup_files/:/var/www/config/
    ports:
      - "8080:80"
      - "8022:22"
      - "8025:25"
      - "8443:443"
    stdin_open: true
    tty: true
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_PORT: 3306
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: dbpass
    ports:
    - "8004:80"
    restart: always
    depends_on: 
    - db 
