FROM centos:centos6
MAINTAINER griffithmail@gmail.com

# Install varioius utilities
RUN yum -y install curl wget unzip git vim \
iproute python-setuptools hostname inotify-tools yum-utils which \
epel-release openssh-server openssh-clients

# Configure SSH
RUN ssh-keygen -b 1024 -t rsa -f /etc/ssh/ssh_host_key \
&& ssh-keygen -b 1024 -t rsa -f /etc/ssh/ssh_host_rsa_key \
&& ssh-keygen -b 1024 -t dsa -f /etc/ssh/ssh_host_dsa_key \
&& sed -ri 's/UsePAM yes/#UsePAM yes/g' /etc/ssh/sshd_config \
&& sed -ri 's/#UsePAM no/UsePAM no/g' /etc/ssh/sshd_config

# Set root password
RUN echo root:password | chpasswd && yum install -y passwd

# Supervisor
RUN yum -y update && \
yum -y install -y epel-release && \
yum install -y iproute python-setuptools hostname inotify-tools yum-utils which && \ 
yum -y install supervisor && \
yum clean all

# Install Apache, exim
RUN yum -y install httpd mod_ssl exim

# Install PHP 5.3
RUN yum -y install php php-devel php-gd php-pdo php-soap php-xmlrpc php-xml php-common php-intl php-jsonlint php-mbstring php-pecl-zip composer php-mysql php-justinrainbow-json-schema5 php-symfony-browser-kit php-paragonie-random-compat php-pecl-yaml php_mysqli php_pdo_mysql php_pdo_sqlite php_xsl php-pear

# Configure Apache
RUN sed -i 's/AllowOverride None/AllowOverride All/g' /etc/httpd/conf/httpd.conf \
&& chown root:apache /var/www/html \
&& chmod g+s /var/www/html

# NodeJS
RUN curl --silent --location https://rpm.nodesource.com/setup_6.x | bash - \
&& yum -y install nodejs gcc-c++ make \
&& npm install -g npm \
&& npm install -g gulp grunt-cli

# UTC Timezone & Networking
RUN ln -sf /usr/share/zoneinfo/UTC /etc/localtime \
	&& echo "NETWORKING=yes" > /etc/sysconfig/network

# Pear 
RUN pear install \
XML_Parser \
XML_Util \
XML_Serializer-0.20.2

COPY dockerfiles/webserver/supervisord.conf /etc/supervisord.conf
EXPOSE 22 25 80 443 3306
CMD ["/usr/bin/supervisord"]

